apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #Recycle
  storageClassName: standard 
  hostPath:
    path: /mystorage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-pvc
  namespace: python-k8s-poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: python-app-pv
